//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEVONEBot.Models.Sev1BotModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sev1WorkersData
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string IncidentId { get; set; }
        public string Owner { get; set; }
    }
}
